version: '3.8'

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - 5000:80
    volumes:
      - ./laravel:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=jeux
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - mysql

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: python_app
    # restart: unless-stopped
    volumes:
      - ./python:/app
    ports:
      - 8000:8000
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=jeux
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - mysql  

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jeux
    volumes:
    - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
