# Generated by Django 3.2.25 on 2024-06-22 06:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_connexion', models.DateTimeField(default=django.utils.timezone.now)),
                ('motDePasse', models.CharField(max_length=128)),
                ('pseudo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_joueur', models.IntegerField()),
                ('nombre_des', models.IntegerField()),
                ('nombre_partie', models.IntegerField()),
                ('temps_attente', models.IntegerField()),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('joueur_createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_crees', to='app.joueur')),
                ('joueurs_challengers', models.ManyToManyField(related_name='sessions_rejointes', to='app.Joueur')),
            ],
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.IntegerField()),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.joueur')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='app.session')),
            ],
        ),
    ]
