# Generated by Django 3.2.25 on 2024-06-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='joueur_createur',
        ),
    ]
